name: franchise_master_app
description: "Franchise Master App for multi-outlet tracking and management."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Enterprise Stack ---
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  injectable: ^2.4.1
  go_router: ^14.0.2
  dio: ^5.4.3
  retrofit: ^4.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1 # Add this line
  dartz: ^0.10.1
  envied: ^0.5.4+1
dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- Code Generators (Developer Tools) ---
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  retrofit_generator: ^8.1.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  envied_generator: ^0.5.4
flutter:
  uses-material-design: true